name: CI/CD Pipeline with ServiceNow Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install requests

      - name: Run Build
        env:
          SERVICENOW_EMAIL: ${{ secrets.SERVICENOW_EMAIL }}
          SERVICENOW_PASSWORD: ${{ secrets.SERVICENOW_PASSWORD }}
        run: |
          python scripts/build.py || (
            curl -X POST "https://dev199705.service-now.com/api/now/table/incident" \
            -u "$SERVICENOW_EMAIL:$SERVICENOW_PASSWORD" \
            -H "Content-Type: application/json" \
            -d '{
                  "short_description": "Pipeline Failed: Build Pipeline",
                  "description": "The build pipeline encountered an error during execution.",
                  "urgency": "1",
                  "impact": "1",
                  "category": "Software",
                  "subcategory": "Build Pipeline"
                }'
          )

      - name: Resolve Incident (if successful)
        if: success()
        env:
          SERVICENOW_EMAIL: ${{ secrets.SERVICENOW_EMAIL }}
          SERVICENOW_PASSWORD: ${{ secrets.SERVICENOW_PASSWORD }}
        run: |
          curl -X PATCH "https://dev199705.service-now.com/api/now/table/incident/<incident_sys_id_here>" \
          -u "$SERVICENOW_EMAIL:$SERVICENOW_PASSWORD" \
          -H "Content-Type: application/json" \
          -d '{
                "state": "Resolved",
                "comments": "Pipeline completed successfully."
              }'
